// Auto-generated. Do not edit!

// (in-package battery_simulator.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class battery_simGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.charge_state = null;
    }
    else {
      if (initObj.hasOwnProperty('charge_state')) {
        this.charge_state = initObj.charge_state
      }
      else {
        this.charge_state = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type battery_simGoal
    // Serialize message field [charge_state]
    bufferOffset = _serializer.bool(obj.charge_state, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type battery_simGoal
    let len;
    let data = new battery_simGoal(null);
    // Deserialize message field [charge_state]
    data.charge_state = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'battery_simulator/battery_simGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd9fe0035ae38454c245737178227ebba';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    bool charge_state
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new battery_simGoal(null);
    if (msg.charge_state !== undefined) {
      resolved.charge_state = msg.charge_state;
    }
    else {
      resolved.charge_state = false
    }

    return resolved;
    }
};

module.exports = battery_simGoal;
