; Auto-generated. Do not edit!


(cl:in-package arm_client-msg)


;//! \htmlinclude battery_simResult.msg.html

(cl:defclass <battery_simResult> (roslisp-msg-protocol:ros-message)
  ((battery_status
    :reader battery_status
    :initarg :battery_status
    :type cl:string
    :initform ""))
)

(cl:defclass battery_simResult (<battery_simResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <battery_simResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'battery_simResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_client-msg:<battery_simResult> is deprecated: use arm_client-msg:battery_simResult instead.")))

(cl:ensure-generic-function 'battery_status-val :lambda-list '(m))
(cl:defmethod battery_status-val ((m <battery_simResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_client-msg:battery_status-val is deprecated.  Use arm_client-msg:battery_status instead.")
  (battery_status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <battery_simResult>) ostream)
  "Serializes a message object of type '<battery_simResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'battery_status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'battery_status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <battery_simResult>) istream)
  "Deserializes a message object of type '<battery_simResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'battery_status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'battery_status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<battery_simResult>)))
  "Returns string type for a message object of type '<battery_simResult>"
  "arm_client/battery_simResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'battery_simResult)))
  "Returns string type for a message object of type 'battery_simResult"
  "arm_client/battery_simResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<battery_simResult>)))
  "Returns md5sum for a message object of type '<battery_simResult>"
  "166ec5ba8d3440019d43d7ce66a808f8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'battery_simResult)))
  "Returns md5sum for a message object of type 'battery_simResult"
  "166ec5ba8d3440019d43d7ce66a808f8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<battery_simResult>)))
  "Returns full string definition for message of type '<battery_simResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Part 2: the result, to be sent by the server upon completion~%#~%# How much time we waited~%string battery_status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'battery_simResult)))
  "Returns full string definition for message of type 'battery_simResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Part 2: the result, to be sent by the server upon completion~%#~%# How much time we waited~%string battery_status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <battery_simResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'battery_status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <battery_simResult>))
  "Converts a ROS message object to a list"
  (cl:list 'battery_simResult
    (cl:cons ':battery_status (battery_status msg))
))
