; Auto-generated. Do not edit!


(cl:in-package battery_simulator-msg)


;//! \htmlinclude battery_simFeedback.msg.html

(cl:defclass <battery_simFeedback> (roslisp-msg-protocol:ros-message)
  ((battery_percentage
    :reader battery_percentage
    :initarg :battery_percentage
    :type cl:float
    :initform 0.0))
)

(cl:defclass battery_simFeedback (<battery_simFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <battery_simFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'battery_simFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name battery_simulator-msg:<battery_simFeedback> is deprecated: use battery_simulator-msg:battery_simFeedback instead.")))

(cl:ensure-generic-function 'battery_percentage-val :lambda-list '(m))
(cl:defmethod battery_percentage-val ((m <battery_simFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader battery_simulator-msg:battery_percentage-val is deprecated.  Use battery_simulator-msg:battery_percentage instead.")
  (battery_percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <battery_simFeedback>) ostream)
  "Serializes a message object of type '<battery_simFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'battery_percentage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <battery_simFeedback>) istream)
  "Deserializes a message object of type '<battery_simFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'battery_percentage) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<battery_simFeedback>)))
  "Returns string type for a message object of type '<battery_simFeedback>"
  "battery_simulator/battery_simFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'battery_simFeedback)))
  "Returns string type for a message object of type 'battery_simFeedback"
  "battery_simulator/battery_simFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<battery_simFeedback>)))
  "Returns md5sum for a message object of type '<battery_simFeedback>"
  "ca45917b08bc55d25401770d33c48e8b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'battery_simFeedback)))
  "Returns md5sum for a message object of type 'battery_simFeedback"
  "ca45917b08bc55d25401770d33c48e8b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<battery_simFeedback>)))
  "Returns full string definition for message of type '<battery_simFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 battery_percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'battery_simFeedback)))
  "Returns full string definition for message of type 'battery_simFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 battery_percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <battery_simFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <battery_simFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'battery_simFeedback
    (cl:cons ':battery_percentage (battery_percentage msg))
))
