; Auto-generated. Do not edit!


(cl:in-package battery_simulator-msg)


;//! \htmlinclude battery_simGoal.msg.html

(cl:defclass <battery_simGoal> (roslisp-msg-protocol:ros-message)
  ((charge_state
    :reader charge_state
    :initarg :charge_state
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass battery_simGoal (<battery_simGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <battery_simGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'battery_simGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name battery_simulator-msg:<battery_simGoal> is deprecated: use battery_simulator-msg:battery_simGoal instead.")))

(cl:ensure-generic-function 'charge_state-val :lambda-list '(m))
(cl:defmethod charge_state-val ((m <battery_simGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader battery_simulator-msg:charge_state-val is deprecated.  Use battery_simulator-msg:charge_state instead.")
  (charge_state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <battery_simGoal>) ostream)
  "Serializes a message object of type '<battery_simGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'charge_state) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <battery_simGoal>) istream)
  "Deserializes a message object of type '<battery_simGoal>"
    (cl:setf (cl:slot-value msg 'charge_state) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<battery_simGoal>)))
  "Returns string type for a message object of type '<battery_simGoal>"
  "battery_simulator/battery_simGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'battery_simGoal)))
  "Returns string type for a message object of type 'battery_simGoal"
  "battery_simulator/battery_simGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<battery_simGoal>)))
  "Returns md5sum for a message object of type '<battery_simGoal>"
  "d9fe0035ae38454c245737178227ebba")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'battery_simGoal)))
  "Returns md5sum for a message object of type 'battery_simGoal"
  "d9fe0035ae38454c245737178227ebba")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<battery_simGoal>)))
  "Returns full string definition for message of type '<battery_simGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%bool charge_state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'battery_simGoal)))
  "Returns full string definition for message of type 'battery_simGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%bool charge_state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <battery_simGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <battery_simGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'battery_simGoal
    (cl:cons ':charge_state (charge_state msg))
))
