// Generated by gencpp from file husky_vel/StopHusky.msg
// DO NOT EDIT!


#ifndef HUSKY_VEL_MESSAGE_STOPHUSKY_H
#define HUSKY_VEL_MESSAGE_STOPHUSKY_H

#include <ros/service_traits.h>


#include <husky_vel/StopHuskyRequest.h>
#include <husky_vel/StopHuskyResponse.h>


namespace husky_vel
{

struct StopHusky
{

typedef StopHuskyRequest Request;
typedef StopHuskyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopHusky
} // namespace husky_vel


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::husky_vel::StopHusky > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::husky_vel::StopHusky&) { return value(); }
};

template<>
struct DataType< ::husky_vel::StopHusky > {
  static const char* value()
  {
    return "husky_vel/StopHusky";
  }

  static const char* value(const ::husky_vel::StopHusky&) { return value(); }
};


// service_traits::MD5Sum< ::husky_vel::StopHuskyRequest> should match
// service_traits::MD5Sum< ::husky_vel::StopHusky >
template<>
struct MD5Sum< ::husky_vel::StopHuskyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::husky_vel::StopHusky >::value();
  }
  static const char* value(const ::husky_vel::StopHuskyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_vel::StopHuskyRequest> should match
// service_traits::DataType< ::husky_vel::StopHusky >
template<>
struct DataType< ::husky_vel::StopHuskyRequest>
{
  static const char* value()
  {
    return DataType< ::husky_vel::StopHusky >::value();
  }
  static const char* value(const ::husky_vel::StopHuskyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::husky_vel::StopHuskyResponse> should match
// service_traits::MD5Sum< ::husky_vel::StopHusky >
template<>
struct MD5Sum< ::husky_vel::StopHuskyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::husky_vel::StopHusky >::value();
  }
  static const char* value(const ::husky_vel::StopHuskyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_vel::StopHuskyResponse> should match
// service_traits::DataType< ::husky_vel::StopHusky >
template<>
struct DataType< ::husky_vel::StopHuskyResponse>
{
  static const char* value()
  {
    return DataType< ::husky_vel::StopHusky >::value();
  }
  static const char* value(const ::husky_vel::StopHuskyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUSKY_VEL_MESSAGE_STOPHUSKY_H
