// Generated by gencpp from file husky_vel/StopHuskyRequest.msg
// DO NOT EDIT!


#ifndef HUSKY_VEL_MESSAGE_STOPHUSKYREQUEST_H
#define HUSKY_VEL_MESSAGE_STOPHUSKYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace husky_vel
{
template <class ContainerAllocator>
struct StopHuskyRequest_
{
  typedef StopHuskyRequest_<ContainerAllocator> Type;

  StopHuskyRequest_()
    {
    }
  StopHuskyRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::husky_vel::StopHuskyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_vel::StopHuskyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopHuskyRequest_

typedef ::husky_vel::StopHuskyRequest_<std::allocator<void> > StopHuskyRequest;

typedef boost::shared_ptr< ::husky_vel::StopHuskyRequest > StopHuskyRequestPtr;
typedef boost::shared_ptr< ::husky_vel::StopHuskyRequest const> StopHuskyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_vel::StopHuskyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_vel::StopHuskyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace husky_vel

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::husky_vel::StopHuskyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_vel::StopHuskyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_vel::StopHuskyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_vel::StopHuskyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_vel::StopHuskyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_vel::StopHuskyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_vel::StopHuskyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::husky_vel::StopHuskyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_vel::StopHuskyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_vel/StopHuskyRequest";
  }

  static const char* value(const ::husky_vel::StopHuskyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_vel::StopHuskyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::husky_vel::StopHuskyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_vel::StopHuskyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopHuskyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_vel::StopHuskyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::husky_vel::StopHuskyRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_VEL_MESSAGE_STOPHUSKYREQUEST_H
