// Generated by gencpp from file arm_client/battery_simResult.msg
// DO NOT EDIT!


#ifndef ARM_CLIENT_MESSAGE_BATTERY_SIMRESULT_H
#define ARM_CLIENT_MESSAGE_BATTERY_SIMRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_client
{
template <class ContainerAllocator>
struct battery_simResult_
{
  typedef battery_simResult_<ContainerAllocator> Type;

  battery_simResult_()
    : battery_status()  {
    }
  battery_simResult_(const ContainerAllocator& _alloc)
    : battery_status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _battery_status_type;
  _battery_status_type battery_status;





  typedef boost::shared_ptr< ::arm_client::battery_simResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_client::battery_simResult_<ContainerAllocator> const> ConstPtr;

}; // struct battery_simResult_

typedef ::arm_client::battery_simResult_<std::allocator<void> > battery_simResult;

typedef boost::shared_ptr< ::arm_client::battery_simResult > battery_simResultPtr;
typedef boost::shared_ptr< ::arm_client::battery_simResult const> battery_simResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_client::battery_simResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_client::battery_simResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_client::battery_simResult_<ContainerAllocator1> & lhs, const ::arm_client::battery_simResult_<ContainerAllocator2> & rhs)
{
  return lhs.battery_status == rhs.battery_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_client::battery_simResult_<ContainerAllocator1> & lhs, const ::arm_client::battery_simResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arm_client::battery_simResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_client::battery_simResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_client::battery_simResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_client::battery_simResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_client::battery_simResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_client::battery_simResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_client::battery_simResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "166ec5ba8d3440019d43d7ce66a808f8";
  }

  static const char* value(const ::arm_client::battery_simResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x166ec5ba8d344001ULL;
  static const uint64_t static_value2 = 0x9d43d7ce66a808f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_client::battery_simResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_client/battery_simResult";
  }

  static const char* value(const ::arm_client::battery_simResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_client::battery_simResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Part 2: the result, to be sent by the server upon completion\n"
"#\n"
"# How much time we waited\n"
"string battery_status\n"
;
  }

  static const char* value(const ::arm_client::battery_simResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_client::battery_simResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.battery_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct battery_simResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_client::battery_simResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_client::battery_simResult_<ContainerAllocator>& v)
  {
    s << indent << "battery_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.battery_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CLIENT_MESSAGE_BATTERY_SIMRESULT_H
