// Generated by gencpp from file arm_client/battery_simActionGoal.msg
// DO NOT EDIT!


#ifndef ARM_CLIENT_MESSAGE_BATTERY_SIMACTIONGOAL_H
#define ARM_CLIENT_MESSAGE_BATTERY_SIMACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <arm_client/battery_simGoal.h>

namespace arm_client
{
template <class ContainerAllocator>
struct battery_simActionGoal_
{
  typedef battery_simActionGoal_<ContainerAllocator> Type;

  battery_simActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  battery_simActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::arm_client::battery_simGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::arm_client::battery_simActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_client::battery_simActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct battery_simActionGoal_

typedef ::arm_client::battery_simActionGoal_<std::allocator<void> > battery_simActionGoal;

typedef boost::shared_ptr< ::arm_client::battery_simActionGoal > battery_simActionGoalPtr;
typedef boost::shared_ptr< ::arm_client::battery_simActionGoal const> battery_simActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_client::battery_simActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_client::battery_simActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_client::battery_simActionGoal_<ContainerAllocator1> & lhs, const ::arm_client::battery_simActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_client::battery_simActionGoal_<ContainerAllocator1> & lhs, const ::arm_client::battery_simActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arm_client::battery_simActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_client::battery_simActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_client::battery_simActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_client::battery_simActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_client::battery_simActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_client::battery_simActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_client::battery_simActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75b7a5301ebeb807cc0fc9197f982eb1";
  }

  static const char* value(const ::arm_client::battery_simActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75b7a5301ebeb807ULL;
  static const uint64_t static_value2 = 0xcc0fc9197f982eb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_client::battery_simActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_client/battery_simActionGoal";
  }

  static const char* value(const ::arm_client::battery_simActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_client::battery_simActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"battery_simGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: arm_client/battery_simGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# This is an action definition file, which has three parts: the goal, the\n"
"# result, and the feedback.\n"
"#\n"
"# Part 1: the goal, to be sent by the client\n"
"#\n"
"# The amount of time we want to wait\n"
"bool charge_state\n"
;
  }

  static const char* value(const ::arm_client::battery_simActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_client::battery_simActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct battery_simActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_client::battery_simActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_client::battery_simActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::arm_client::battery_simGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CLIENT_MESSAGE_BATTERY_SIMACTIONGOAL_H
